using System;
using System.Collections.Generic;
using System.Text;

namespace ShoppingCart.Domain.Models
{
    public class OrderDetails
    {
        //TO MAKE AUTOGENERATED
        public int Id { get; set; }
        //TO ADD THE FOREIGN KEY ATTRIBUTE
        public Guid ProductFK { get; set; }
        public virtual Product Product { get; set; }

        // TO ADD FOREIGN KEY ATTRIBUTE
        public Guid OrderFK { get; set; }
        public virtual Product Order { get; set; }

        public int Quantity { get; set; }

        public double SoldPrice { get; set; }
    }
}
